bird_tracker/urls.py
from . import views
from django.urls import path, include

# the urls for the respective views
urlpatterns = [
    path('', views.BirdList.as_view(), name='home'),
    path('daily_data_forms/<int:id>', views.daily_data_form, name='daily_data_form'),  # noqa
    path('daily_data_edit/<int:id>', views.daily_data_edit, name='daily_data_edit'),   # noqa
    path('add_new_bird_form/', views.add_new_bird_form, name='add_new_bird_form'),  # noqa
    path('bird_detail/<int:id>/', views.bird_detail, name='bird_detail'),
    path('<int:id>/edit_bird/', views.bird_edit, name='bird_edit'),   # noqa
    path('bird_detail/<int:id>/delete_bird/', views.bird_delete, name='bird_delete'),   # noqa
    path('qr_code/', views.qr_code_show, name='qr_code'),

]

raptor_health/urls.py
"""
URL configuration for raptor_health project.
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path('accounts/', include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('', include("bird_tracker.urls")),
     # Password reset URLs
     path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
   
]

bird_tracker/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.timezone import now


# Constants to be used in the Bird and DailyData Model
SEX = ((0, "Female"), (1, "Male"), (2, "Unknown"))
WEATHER = ((0, "Rainy"), (1, "Sunny"), (2, "Windy"), (3, "Cold"))
TRAINING = ((0, "No Training"), (1, "Faustappel"), (2, "Free Flight"), (3, "Lure Flying"))
BEHAVIOUR = ((0, "Motivated"), (1, "Lethargic"), (2, "Aggressive"), (3, "Unmotivated"), (4, "Slightly Unmotivated"), (5, "Neutral"))
# aggressive, lethargic, unmotivated, slightly unmotivated,
# Bird Custom Model


class Bird(models.Model):
    """
    Stores a single bird instance.foreign key : bird_id
    """
    bird_name = models.CharField(max_length=20, unique=True, blank=False)
    type = models.CharField(max_length=20, blank=False)
    sex = models.IntegerField(choices=SEX, default=0, null=False)
    date_of_birth = models.CharField(max_length=20, default="Unknown")
    target_weight = models.PositiveSmallIntegerField(null=True, blank=True, validators=[
            MinValueValidator(0), 
            MaxValueValidator(20000)   
        ])
    additional_info = models.CharField(max_length=200, blank=False)
    created_on = models.DateTimeField(auto_now_add=True, null=False)
    main_image = CloudinaryField('image', default='placeholder', format='jpg')

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return (f"{self.bird_name} | {self.type}")

# Daily data custom model


class DailyData(models.Model):
    """
    Stores a single instance of required
     daily data :model: `selected_bird.Bird`
    :model: `trainer.User`
    """
    selected_bird = models.ForeignKey(
        Bird, on_delete=models.CASCADE, related_name='selected_bird')
    trainer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='trainer')
    date = models.DateTimeField(default=now, null=False) 
    weight = models.PositiveSmallIntegerField(null=False)
    food_type = models.CharField(max_length=12, blank=False)
    food_weight = models.PositiveSmallIntegerField(null=False)
    food_time = models.TimeField(null=True, blank=True)
    weather = models.IntegerField(choices=WEATHER, default=1, null=False)
    temperature = models.IntegerField(null=False,  validators=[
            MinValueValidator(-50), 
            MaxValueValidator(50)   
        ])
    training = models.IntegerField(choices=TRAINING, default=0, null=False)
    training_time = models.TimeField(null=True, blank=True)
    training_motivation = models.IntegerField(null=True, blank=True, validators = [
        MinValueValidator(1),
        MaxValueValidator(10)
    ])
    behaviour = models.IntegerField(choices=BEHAVIOUR, default=0, null=False)
    notable_info = models.CharField(
        max_length=200, blank=False, default="None")
    notable_image = CloudinaryField('image', default='placeholder')

    class Meta:
        ordering = ["-date"]

    def __str__(self):
        return (f"Bird {self.selected_bird} Trained by {self.trainer} | {self.date}")  # noqa

bird_tracker/forms.py
from .models import DailyData
from django.forms import DateTimeInput
from .models import Bird
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from django.forms import TimeInput
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from allauth.account.forms import SignupForm



# unicode for degree celsius
deg = '\u00B0C'


class AddNewBirdForm(forms.ModelForm):
    class Meta:
        model = Bird
        fields = ('bird_name', 'type', 'sex', 'date_of_birth', 'target_weight',
                  'additional_info', 'main_image')
        labels = {
            'date_of_birth': 'Date of Birth:      format: YYYY-MM-DD',
            'target_weight': 'Target Weight in Grams'
        }


class DailyDataForm(forms.ModelForm):
    class Meta:
        model = DailyData
        fields = ('date','weight', 'food_type', 'food_weight', 'food_time',
                  'weather', 'temperature', 'training', 'training_motivation', 'training_time', 'behaviour',
                  'notable_info', 'notable_image')
        labels = {
            'date': 'Date: (please enter the time and date)', 'weight': 'Weight:  (please enter the bird\'s weight in grams)',
            'food_type': 'Food Type:  (mouse, chicken, etc)',
            'food_weight': 'Food Weight:  (food weight in grams)',
            'food_time': 'Feeding Time: (time of feeding)',
            'temperature': 'Temperature:  (the air temperature in °C)',
            'training': 'Training  (the type of training that was performed)',
            'training_time': 'Time of Training:  (time of the Training)',
            'behaviour': 'Behaviour  (the general mood of the bird)',
            'notable_info': 'Notable Information (any extra info - missing feathers, injuries, loss of appetite, moulting etc)',  # noqa
            'notable_image': 'Add an image of anything noteworthy',
        }
        widgets = {
            'training_motivation': forms.HiddenInput(),
            'date': DateTimeInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'training_time': TimeInput(attrs={'type': 'time'}),
            'food_time': TimeInput(attrs={'type': 'time'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'weight',
            'food_type',
            'food_weight',
            'food_time',
            'weather',
            'temperature',
            'training',
            Field('training_motivation', type="hidden"),  # Explicitly set as hidden
            'training_time',
            'behaviour',
            'notable_info',
            'notable_image',
        )
        self.fields['date'].input_formats = ['%Y-%m-%dT%H:%M']

bird_tracker/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.http import HttpResponse
import os
import json
from django.shortcuts import render
from django.views import generic
from .models import Bird, DailyData
from .forms import AddNewBirdForm, DailyDataForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from cloudinary.exceptions import Error as CloudinaryError
from django.utils.timezone import now
from django.shortcuts import redirect
from django.forms import TimeInput


# built in django view
class BirdList(generic.ListView):
    queryset = Bird.objects.all()
    template_name = "bird_tracker/index.html"


# view to display bird details
def bird_detail(request, id):
    """display a list of the birds details
    and all daily data that is required
    ***Template
    bird_tracker/bird_detail.html"""
    queryset = Bird.objects.all()
    bird_detail = get_object_or_404(queryset, id=id)
    selected_bird = bird_detail.selected_bird.all()
    selected_bird_json = bird_detail.selected_bird.all().values(
       "behaviour","date", "food_time", "food_type", "food_weight", "id", "notable_info", "selected_bird", "selected_bird_id", "temperature", "trainer", "trainer_id", "training", "training_time", "weather", "weight", "training_motivation", "notable_info", "notable_image",
    ) 
    for data in selected_bird_json:
        data["target_weight"] = bird_detail.target_weight
      # Convert QuerySet to a list and handle datetime fields
    selected_bird_list = list(selected_bird_json)
    for bird in selected_bird_list:
        if "date" in bird and bird["date"] is not None:
            bird["date"] = bird["date"].isoformat()
        if bird["training_time"]:
            if isinstance(bird["training_time"], str):
                pass
            else:
                bird["training_time"] = bird["training_time"].strftime('%H:%M:%S')
                
        if bird["food_time"]:
           bird["food_time"] = bird["food_time"].strftime('%H:%M:%S')
        if bird["notable_image"]:
           bird["notable_image"] = bird["notable_image"].url  # Include the Cloudinary image URL

     # Convert the QuerySet to JSON
    selected_bird_json = json.dumps(selected_bird_list)
    

    return render(
        request,
        "bird_tracker/bird_detail.html",
        {"bird_detail": bird_detail,
         "selected_bird": selected_bird,
         "selected_bird_json": selected_bird_json,
         "target_weight": bird_detail.target_weight, 
         },
    )
    
    
# View for the daily data form
def daily_data_form(request, id):
    """Form handler for adding daily data for a bird.
    Template: bird_tracker/daily_data_form.html"""
    bird_detail = get_object_or_404(Bird, id=id)
    selected_bird = bird_detail.selected_bird.all()
    
    if request.method == "POST":
        form = DailyDataForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                daily_data = form.save(commit=False)
                daily_data.trainer = request.user
                daily_data.selected_bird = bird_detail
                daily_data.save()
                messages.success(request, 'Daily Data added successfully.')
                # return render(request, "bird_tracker/bird_detail.html",
                #               {"bird_detail": bird_detail, "selected_bird": selected_bird})  # noqa
                return redirect('bird_detail', id=bird_detail.id)
            except CloudinaryError as e:
                messages.add_message(
                    request, messages.ERROR,
                    f'Error uploading image: {str(e)}'
                )
                form = DailyDataForm(request.POST)
                return render(request, "bird_tracker/daily_data_form.html",
                              {"daily_data_form": form,
                               "bird_detail": bird_detail,
                               "selected_bird": selected_bird,
                               "motivation_range": range(1, 11),
                               "view": "add",
                               })

        elif not form.is_valid():
            messages.error(request, 'Please check the entered data.')
            form = DailyDataForm(request.POST)
            return render(request, "bird_tracker/daily_data_form.html",
                          {"daily_data_form": form,
                           "bird_detail": bird_detail,
                           "selected_bird": selected_bird,
                           "motivation_range": range(1, 11),
                           "view": "add",})
            
            
            

    else:
        form = DailyDataForm(initial={'date': now()})
        
    return render(request, "bird_tracker/daily_data_form.html",
                      {"daily_data_form": form,
                       "bird_detail": bird_detail,
                       "selected_bird": selected_bird,
                       "motivation_range": range(1, 11),
                       "view": "add",
                       }
                      
                      )
    

# view for the add new bird form
def add_new_bird_form(request):
    """Add new bird form. Adds all required data for a bird instance
    ***Template
    # bird_tracker/add_new_bird_form"""
    if request.method == "POST":
        add_new_bird_form = AddNewBirdForm(request.POST, request.FILES)
        if add_new_bird_form.is_valid():
            try:
                new_bird = add_new_bird_form.save()
                messages.add_message(
                    request, messages.SUCCESS,
                    'New Bird added'
                )
                return HttpResponseRedirect(reverse('home'))

            except CloudinaryError as e:
                messages.add_message(
                    request, messages.ERROR,
                    f'Error uploading image: {str(e)}'
                )

                return render(
                    request,
                    "bird_tracker/add_new_bird_form.html",
                    {
                        "view": "add",
                        "add_new_bird_form": add_new_bird_form,
                    },
                ) 
        else:
            messages.add_message(
                request, messages.ERROR,
                'Please check the entered Data'
            )

            add_new_bird_form = AddNewBirdForm(request.POST, request.FILES)
            return render(
                request,
                "bird_tracker/add_new_bird_form.html",
                {
                    "view": "add",
                    "add_new_bird_form": add_new_bird_form,
                },
            )

    else:
        add_new_bird_form = AddNewBirdForm()
        return render(
            request,
            "bird_tracker/add_new_bird_form.html",
            {
                "view": "add",
                "add_new_bird_form": add_new_bird_form,
            },
        )
    

# view to edit bird form
def bird_edit(request, id):
    """
    View to edit bird information.
    Template: "bird_tracker/add_new_bird_form.html"
    """
    queryset = Bird.objects.all()
    bird = get_object_or_404(queryset, id=id)
    context = {"view": "edit_bird"}

    if request.method == "POST":
        edit_bird_form = AddNewBirdForm(
            request.POST, request.FILES, instance=bird)
        if edit_bird_form.is_valid():
            try:
                edit_bird_form.save()
                messages.success(request, 'Bird Updated!')
                return HttpResponseRedirect(reverse('bird_detail', args=[id]))

            except CloudinaryError as e:
                messages.add_message(
                    request, messages.ERROR,
                    f'Error uploading image: {str(e)}'
                )

        else:
            messages.error(request, 'Error updating bird!')

    else:

        edit_bird_form = AddNewBirdForm(instance=bird)

    return render(
        request,
        "bird_tracker/add_new_bird_form.html",
        {
            "view": "edit",
            "edit_bird_form": edit_bird_form,
            "id": id,
        },
    )
    
 # view to edit the daily data 

def daily_data_edit(request, id):   
    """
    View to edit daily data .
    Template: "bird_tracker/daily_data_form.html"
    """
  
    queryset = DailyData.objects.all()
    daily_data = get_object_or_404(queryset, id=id)    
    bird_data_to_edit = Bird.objects.all()
    bird_detail = get_object_or_404(bird_data_to_edit, id=daily_data.selected_bird_id)
  
    context = {"view": "daily_data_edit"}

    if request.method == "POST":
        edit_daily_data_form = DailyDataForm(
            request.POST, request.FILES, instance=daily_data)
        if edit_daily_data_form.is_valid():
            try:
                edit_daily_data_form.save()
                messages.success(request, 'Daily Data Updated!')
                return redirect('bird_detail', id=bird_detail.id)

            except CloudinaryError as e:
                messages.add_message(
                    request, messages.ERROR,
                    f'Error uploading image: {str(e)}'
                )

        else:
            messages.error(request, 'Error updating Daily Data!')

    else:

        edit_daily_data_form = DailyDataForm(instance=daily_data)
    return render(
        request,
        "bird_tracker/daily_data_form.html",
        {
            "view": "edit",
            "edit_daily_data_form": edit_daily_data_form,
            "id": id,
            "bird_detail": bird_detail,
        },
    )
    

# view to delete bird
def bird_delete(request, id):
    """
    Bird delete View
    """
    queryset = Bird.objects.all()
    bird = get_object_or_404(queryset, id=id)
    # comment = get_object_or_404(Comment, pk=comment_id)
    bird.delete()

bird_tracker/templates/bird_tracker/add_new_bird_form.html
{% extends "base.html" %}
{% block daily_data_form %}
{% load static %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 card mb-4 mt-3 card-bg">
            {% if view == "add" %}
            <ul>
                <li class="li-style">
                    <a class="btn btn-secondary" aria-current="page" href="{% url 'home' %}">Back to Bird
                        List</a>
                </li>
            </ul>

            <div class="card-body d-flex flex-column align-items-center">
                <h3>Please enter the required information:</h3>
                <p>Trainer: {{ user.username }}</p>
                <form id="AddNewBirdForm" method="post" enctype="multipart/form-data"
                    style="margin-top: 1.3em; width: 100%;">
                    {% csrf_token %}
                    {{ add_new_bird_form | crispy }}
                    <button id="submitButton" type="submit" class="btn btn-custom-color-action2">Submit</button>
                </form>
            </div>
            {% elif view == "edit" %}
            <ul>
                <li class="li-style">
                    <a class="btn btn-secondary" aria-current="page" href="{% url 'bird_detail' id %}">Back to Bird
                        Data</a>
                </li>
            </ul>

            <div class="card-body d-flex flex-column align-items-center">
                <h3>Please enter the required information:</h3>
                <p>Trainer: {{ user.username }}</p>
                <form method="post" enctype="multipart/form-data" style="width: 100%;">
                    {% csrf_token %}
                    {{ edit_bird_form | crispy }}
                    <button type="submit" class="btn btn-custom-color-action2">Save changes</button>
                </form>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock daily_data_form %}

bird_tracker/templates/bird_tracker/bird_detail.html
{% extends "base.html" %}{% block bird_detail %} {% load static %} {% load crispy_forms_tags %}
<head>
  <link
    href="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/styles/index.css"
    rel="stylesheet"
  />
  <script src="https://cdn.jsdelivr.net/npm/vanilla-calendar-pro/index.js" defer></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<!-- bird detail.html content starts here -->
<div class="container-fluid main-item">
  <div class="row">
    <!-- Bird detail starts here -->
    <h3 class="heading-bird-data display-4">Bird Data</h3>
    <hr class="divider" />
    <div class="col-md-4">
      <div class="image-container">
        {% if "placeholder" in bird_detail.main_image.url %}
        <img
          id="main-img"
          class="card-img-top"
          src="{% static 'images/default.jpg' %}"
          alt="placeholder image"
        />
        {% else %}
        <img
          class="card-img-top"
          src=" {{ bird_detail.main_image.url }}"
          alt="{{ bird_detail.bird_name }}"
          id="main-img"
        />
        {% endif %}
      </div>
    </div>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <div>
            <p class="lead"><b>Bird Name:</b> {{ bird_detail.bird_name }}</p>
          </div>
          <p class="lead"><b>Type: </b>{{bird_detail.type }}</p>
          <p class="lead"><b>Gender: </b>{{bird_detail.get_sex_display }}</p>
          <p class="lead"><b>Date of Birth:</b> {{bird_detail.date_of_birth}}</p>
          {% if bird_detail.target_weight > 0 %}
          <p class="lead"><b>Target Weight:</b> {{bird_detail.target_weight}}g</p>
          {% else %}
          <p class="lead"><b>Target Weight:</b> None given</p>
          {% endif %}
          <p class="lead"><b>Additional Info: </b>{{bird_detail.additional_info }}</p>
        </div>
      </div>
    </div>

    <div class="col-md-4 button-card">
      <ul>
        <li class="li-style d-grid">
          <a class="btn btn-secondary btn-block" aria-current="page" href="{% url 'home' %}"
            >Back to Bird List</a
          >
        </li>
        {% if user.is_superuser or user.is_staff %}
        <li class="li-style d-grid">
          <a class="btn btn-signup" aria-current="page" href="{% url 'bird_edit' bird_detail.id %}"
            >Edit Bird Data</a
          >
        </li>
        <!-- <li class="li-style d-grid">
          <button class="btn btn-delete btn-block" data-bird-id="{{ selected_bird.id }}">
            Delete Bird
          </button>
        </li> -->
      </ul>
    </div>
    {% endif %}
  </div>
  <!-- The main image Modal -->
  <div id="myModal" class="modal-img">
    <span class="close">×</span>
    <img class="modal-content" id="modal-img" />
    <div id="caption"></div>
  </div>
  <hr class="divider" />
  <!-- Serialize the selected_bird data into a JSON script -->
  {{ selected_bird_json|json_script:"selected_bird_data" }}

  <div class="container-fluid">
    <!-- calendar pop up modal -->
    <div
      class="modal fade"
      id="calendarModal"
      tabindex="-1"
      aria-labelledby="calendarModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="calendarModalLabel">{{bird_detail.bird_name}}</h5>
            <span class="modal-title calendarTagetWeight"
              ><b>Target Weight:</b> {{ bird_detail.target_weight}} grams</span
            >
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body" id="calendarModalBody">
            <!-- Content will be dynamically populated -->
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <!--The Calendar injected here -->
      <div class="col-md-6" id="calendar" data-bird="{{ selected_bird|safe }}"></div>
      <div class="col-md-6 chart-container">
        <div class="btn-chart">
          <button id="dateBack" type="button" class="btn btn-secondary">Back</button>
          <button id="dateForward" type="button" class="btn btn-secondary">Forward</button>
          {% if bird_detail.target_weight > 0 %}
          <button id="birdWeightChart" type="button" class="btn btn-secondary">
            <b>Target Weight: {{bird_detail.target_weight}}g</b>
          </button>
          {% endif %}
          <!-- <button id="birdWeightChart" type="button" class="btn btn-secondary">Bird Weight</button> -->
          <!-- <button id="birdMotivationChart" type="button" class="btn btn-secondary">Motivation</button> -->
        </div>
        <!-- chart injected here-->
        <canvas id="myChart"></canvas>
      </div>
      <!-- <div class="col-md-6 chart-container">
      <canvas id="motivationChart" width="1000px"></canvas> 
      </div> -->
    </div>
  </div>
</div>
{% if user.is_superuser or user.is_staff %}
<div class="daily-button">
  <div class="d-grid">
    <a
      id="addDailyDataButton"
      href="{% url 'daily_data_form'  bird_detail.id %}"
      class="btn btn-custom-color-action3 btn-lg col-8 mx-auto"
      >Add Daily Data for: <br />
      <b>{{bird_detail.bird_name}}</b>
    </a>
  </div>
</div>
{% else %}
<div class="daily-button">
  <div class="d-grid">
    <p class="btn btn-custom-color btn-lg col-8 mx-auto">
      Daily Data for: <br />
      <b>{{bird_detail.bird_name}}</b>
    </p>
  </div>
</div>
{% endif %}

<div class="flex-wrapper">
  <div class="accordion" id="daily_data">
    {% for data in selected_bird %}
    <div id="trainer-info" data-trainer-info="{{ data.trainer|default:'' }}"></div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button
          class="accordion-button"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapse{{ forloop.counter }}"
          aria-expanded="true"
          aria-controls="collapse{{ forloop.counter }}"
        >
          <span class="span-font">Date: {{ data.date }} Trainer: {{ data.trainer }}</span>
          <span class="weight-heading"
            >Weight: <span class="span-data">{{ data.weight}}g</span>
          </span>
          <span class="span-font"
            >Food Weight:<span class="span-data">{{ data.food_weight }}g</span>
          </span>
        </button>
      </h2>
    </div>
    <div
      id="collapse{{ forloop.counter }}"
      class="accordion-collapse collapse"
      data-bs-parent="#daily_data"
    >
      <div class="accordion-body">
        <div class="accordion-text col-md-4">
          <div>
            <p>{{bird_detail}}</p>
            <p><b>Bird Weight: </b>{{ data.weight }} grams</p>
          </div>
          {% if bird_detail.target_weight > 0 %}
          <div>
            <p><b>Target Weight: </b>{{ bird_detail.target_weight }} grams</p>
          </div>
          {% else %}
          <div>
            <p><b>Target Weight: </b>None Given</p>
          </div>
          {% endif %}
          <div>
            <p><b>Type of Food: </b>{{ data.food_type }}</p>
          </div>
          <div>
            <p><b>Weight of Food: </b>{{ data.food_weight }} grams</p>
          </div>
          <div>
            <p><b>Time of feeding: </b>{{ data.food_time }}</p>
          </div>
          <div>
            <p><b>Weather: </b>{{ data.get_weather_display }}</p>
          </div>
          <div>
            <p><b>Temperature: </b>{{ data.temperature }}°C</p>
          </div>
          <div>
            <p><b>Type of training:</b> {{ data.get_training_display }}</p>
          </div>
          <div>
            <p><b>Motivation during Training:</b> {{ data.training_motivation }}</p>
          </div>
          <div>
            <p><b>Time of training:</b> {{ data.training_time }}</p>
          </div>
          <div>
            <p><b>Behaviour/Mood: </b>{{ data.get_behaviour_display }}</p>
          </div>
          <div>
            <p><b>Notable Info:</b> {{ data.notable_info }}</p>
          </div>
          <div class="col-md-3">
            <div class="image-container">
              {% if "placeholder" in data.notable_image.url %}
              <span></span>
              {% else %}
              <img
                class="card-img-top"
                src="{{ data.notable_image.url }}"
                alt="{{ bird.bird_name }}"
              />
              {% endif %}
            </div>
          </div>
          {% if user.is_superuser or user.is_staff %}
          <li class="li-style d-grid">
            <a
              id="edit-data-button-bird-detail"
              class="btn btn-edit-data"
              aria-current="page"
              href="{% url 'daily_data_edit'  data.id %}"
              data-edit-url="{% url 'daily_data_edit' data.id %}"
              >Edit Daily Data</a
            >
          </li>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<!-- Delete confirmation modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Bird?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete the Bird? This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
<div id="bird-info" data-target-weight="{{ bird_detail.target_weight|default:'' }}"></div>
{% if user.is_superuser or user.is_staff %}
<div id="edit-permission" data-user-permission="true"></div>
{% else %}
<div id="edit-permission" data-user-permission="false"></div>

{% endif %} {% endblock bird_detail %} {% block extras %}
<script type="module" src="{% static 'js/calendar.js' %}"></script>
<script type="module" src="{% static 'js/birdData.js' %}"></script>
<script type="module" src="{% static 'js/graph.js' %}"></script>
<script type="module" src="{% static 'js/motivationGraph.js' %}"></script>
{% endblock %}

bird_tracker/templates/bird_tracker/qr-code.html
{% extends "base.html" %}
{% load static %}
{% block qr_code %}
<div>
    <h1 class="qr-heading">Scan the QR-Code to connect a mobile device </h1>
    <img src="{% static 'images/qr_code.png' %}" alt="default QR Code" class="qr-code"/>
    
    <a class="btn btn-secondary btn-block" aria-current="page" href="{% url 'home' %}"
    >Back to Bird List</a
  >
</div>

{% endblock qr_code %}